version: 2.1
commands:
  
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install --prefix src/

  setup-cd:
    steps:
    - run: 
        name: Configure environment
        command: |
          # install terraform
          wget https://releases.hashicorp.com/terraform/0.15.4/terraform_0.15.4_linux_amd64.zip
          unzip terraform_0.15.4_linux_amd64.zip
          chmod +x terraform 
          sudo mv terraform /usr/local/bin/terraform
          cd / && terraform -v
          
          # install helm
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

          # install kubectl
          sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          sudo chmod +x ./kubectl 
          sudo mv ./kubectl /usr/local/bin/kubectl

          # configure kops
          sudo curl -LO https://github.com/kubernetes/kops/releases/download/v1.18.0/kops-linux-amd64
          sudo chmod +x kops-linux-amd64
          sudo mv kops-linux-amd64 /usr/local/bin/kops
          kops export kubecfg rmit.k8s.local --state s3://rmit-kops-state-fnzv31

  smoke-test:
    parameters:
      envName: 
        type: string
        default: "test"
    steps:
      - run:
          name: Smoke test
          command: |
            export endpoint=$(kubectl get service/todo-app -n << parameters.envName >> -o json | jq '.status.loadBalancer.ingress[0].hostname' | sed -e 's/^"//' -e 's/"$//')
            echo $endpoint
            export returncode=$(curl -s -o /dev/null -w "%{http_code}" ${endpoint})
            if [ $returncode -ne "200" ]
            then
              echo "Return Code was not 200, it was: ${returncode}"
              exit 1
            fi

jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output/
    steps:
      - checkout
      - install_deps
 
      - run: |
          cd src/
          npm run test-lint
          npm run test-unit
      
      - store_test_results:
          path: src/test-output/

  integration-test:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output/
    steps:
      - checkout
      - install_deps
      - run:
          name: Run integration tests
          command:
            npm run test-integration --prefix src/
      - store_test_results:
          path: src/test-output/

  e2e:
    docker:
      - image: qawolf/qawolf:v0.9.2
    environment:
      QAW_HEADLESS: true

    steps: 
      - checkout

      - run:
          name: setup
          command: |
            # install kubectl
            curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
            chmod +x ./kubectl 
            mv ./kubectl /usr/local/bin/kubectl

            # configure kops
            curl -LO https://github.com/kubernetes/kops/releases/download/v1.18.0/kops-linux-amd64
            chmod +x kops-linux-amd64
            mv kops-linux-amd64 /usr/local/bin/kops
            kops export kubecfg rmit.k8s.local --state s3://rmit-kops-state-fnzv31

            apt-get install jq -y

      - run:
          name: setup
          command: |
            apt-get install jq -y

      - run: 
          name: End 2 end tests
          no_output_timeout: 2m
          command: |
            export ENDPOINT=http://$(kubectl get service/todo-app -n test -o json | jq '.status.loadBalancer.ingress[0].hostname' | sed -e 's/^"//' -e 's/"$//')
            echo $ENDPOINT
            cd src
            npm install
            npm run test-e2e

  package:
    machine: true
    environment:
      ECR: "020045426932.dkr.ecr.us-east-1.amazonaws.com"
      reponame: "rmit-assignment3-container-repo"
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            mkdir -p artifacts

            # install AWS CLI
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            # instll helm
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      
      - run: 
          name: Build image
          command: |
            cd src
            export IMAGE_TAG=${ECR}/${reponame}:${CIRCLE_SHA1}
            echo ${IMAGE_TAG} > ../artifacts/image.txt
            docker build -t ${IMAGE_TAG} .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR}
            docker push ${IMAGE_TAG}

      - run:
          name: Package helm
          command: | 
            helm package helm/todo --app-version ${CIRCLE_SHA1} -d artifacts

      - run:
          name: Package infra
          command: |
            cp -r infra artifacts/infra

      - store_artifacts: 
          path: ./artifacts

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  deploy-test:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      ENV: test
    parameters:
      environment:
        type: string
        default: test
    steps:
      - attach_workspace:
          at: ./
      - setup-cd 
      - run:
          name: deploy infra
          command: |
            cd artifacts/infra
            make init
            make up

            x=$(terraform output db_endpoint)
            tmpx="${x%\"}"
            DB_URI="${tmpx#\"}"

            y=$(terraform output db_user)
            tmpy="${y%\"}"
            DB_USER="${tmpy#\"}"

            z=$(terraform output db_pass)
            tmpz="${z%\"}"
            DB_PASS="${tmpz#\"}"

            echo mongodb://$DB_USER:$DB_PASS@$DB_URI::27017/ > ../db_connection_string.txt
            cat ../db_connection_string.txt
      - run:
          name: deploy application
          command: 
            helm upgrade todo artifacts/todo-0.1.0.tgz -i -n test --set db_endpoint=$(cat artifacts/db_connection_string.txt),image_id=$(cat artifacts/image.txt),
      
      - smoke-test

  deploy-prod:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      ENV: prod
    parameters:
      environment:
        type: string
        default: prod
    steps:
      - attach_workspace:
          at: ./
      - setup-cd 
      - run:
          name: deploy infra
          command: |
            cd artifacts/infra
            make init
            make up

            x=$(terraform output db_endpoint)
            tmpx="${x%\"}"
            DB_URI="${tmpx#\"}"

            y=$(terraform output db_user)
            tmpy="${y%\"}"
            DB_USER="${tmpy#\"}"

            z=$(terraform output db_pass)
            tmpz="${z%\"}"
            DB_PASS="${tmpz#\"}"

            echo mongodb://$DB_USER:$DB_PASS@$DB_URI::27017/ > ../db_connection_string.txt
            cat ../db_connection_string.txt
                  
      - run:
          name: deploy application
          command: 
            helm upgrade todo artifacts/todo-0.1.0.tgz -i -n prod --set db_endpoint=$(cat artifacts/db_connection_string.txt),image_id=$(cat artifacts/image.txt),
      
      - smoke-test
      
workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - integration-test:
          requires: 
            - build
      - package:
          requires:
            - integration-test
      - deploy-test:
          requires:
            - package
      - e2e:
          requires:
            - deploy-test
      - approval:
          type: approval
          requires:
            - deploy-test
            - e2e
      - deploy-prod:
          requires:
            - approval
      
          
